#!/bin/bash

set -e

case $1 in
    install|upgrade)
		if [ -d /run/systemd/system ] && command -v systemctl >/dev/null 2>&1; then
			systemctl stop rustadmin.service || true
			sleep 1
		fi
		rm -f /usr/bin/libsciter-gtk.so
        ;;
esac

exit 0
