#!/bin/bash

set -e

case $1 in
    remove)
		rm -f /usr/bin/rustadmin
		
		if [ -d /run/systemd/system ] && command -v systemctl >/dev/null 2>&1; then
			systemctl disable --now rustadmin.service || true
			rm -f /etc/systemd/system/rustadmin.service /usr/lib/systemd/system/rustadmin.service
			systemctl daemon-reload || true
			
			# workaround temp dev build between 1.1.9 and 1.2.0
			serverUser=$(ps -ef | grep -E 'rustadmin +--server' | grep -v 'sudo ' | awk '{print $1}' | head -1)
			if [ "$serverUser" != "" ] && [ "$serverUser" != "root" ]
			then
				systemctl --machine=${serverUser}@.host --user stop rustadmin >/dev/null 2>&1 || true
			fi
			rm /usr/lib/systemd/user/rustadmin.service >/dev/null 2>&1 || true
		fi
        ;;
esac

exit 0
